### ISSUE TITLE
No module named 'gi'

### ISSUE THREAD

**Issue by atouu** [ivan-hc/Bottles-appimage#5]
I tried installing `python-gobject` from pacman too, it didn't work. I'm using Artix as my distro.

![Screenshot_2024-03-04_14-21-37](https://github.com/ivan-hc/Bottles-appimage/assets/67765922/98d74049-59ab-4520-84e5-b9e01b7abb6b)

**Comment by ivan-hc** [comment]
I think that this is because the AppImage only take care of modules in the AppImage itself. the counterpart of site-packages from Arch, in Debian, is dist-packages, and the module is there.

I've rebuilt the AppImage on my Debian Testing and included also the modules from Arch Linux.

At the end of this workflow run https://github.com/ivan-hc/Bottles-appimage/actions/runs/8137165140 download the AppImage again. It will be about 10 MB bigger, but should work, this time.

**Comment by ivan-hc** [comment]
@atouu can you confirm that this works for you?

**Comment by ivan-hc** [comment]
I close this issue. Feel free to reopen it if the problem persists.

**Comment by atouu** [comment]
@ivan-hc  Sorry for the late response. The problem is still there but with more errors now
![image](https://github.com/ivan-hc/Bottles-appimage/assets/67765922/fd0b1607-5940-4842-a021-d2e2ac68c37c)

**Comment by ivan-hc** [comment]
I cannot find such module anywhere. Not in JuNest, nor in the Debian side of the built package.

I'll try to add "package_index.py" from .junest/usr/lib/python3.11/site-packages/setuptools into the AppImage

It would be useful if you run the [bottles.sh](https://github.com/ivan-hc/Bottles-appimage/blob/main/bottles.sh) script on your PC and investigate on this issue with me.

**Comment by ivan-hc** [comment]
I've included _socket module in lib-dynload and the latter is in now in PYTHONPATH, near site-packages https://github.com/ivan-hc/Bottles-appimage/commit/cb62da3ed5515edb8d8f5e9ee155cff6936c3f7c

at the end of this workflow download and test the new AppImage https://github.com/ivan-hc/Bottles-appimage/actions/runs/8369015691

This is the second module I've included from Arch Linux, according to this issue.

If you face other problems, reopen this issue. Also let me know if all works well.

For now, I close this one.
